import type { CodegenConfig } from '../config/types'

/**
 * Render the multi-line header each generated file starts with.
 * `config.license === false` omits the SPDX marker entirely; `undefined`
 * uses the MIT default; anything else is emitted verbatim after
 * `SPDX-License-Identifier:`.
 */
export function codegenHeader(config?: Partial<CodegenConfig>, extra?: string): string {
  const lines: string[] = []
  const license = config?.license
  if (license !== false) {
    lines.push(`// SPDX-License-Identifier: ${license ?? 'MIT'}`)
  }
  lines.push('// Auto-generated by Polyq — do not edit')
  if (extra) lines.push(extra)
  return lines.join('\n')
}
