import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'pathe'
import consola from 'consola'
import type { CodegenConfig } from '../../config/types'
import type { CodegenOutput } from '../types'

const logger = consola.withTag('polyq:evm-codegen')

interface AbiItem {
  type: 'function' | 'event' | 'error' | 'constructor' | 'fallback' | 'receive'
  name?: string
  inputs?: AbiParam[]
  outputs?: AbiParam[]
  stateMutability?: 'pure' | 'view' | 'nonpayable' | 'payable'
  anonymous?: boolean
}

interface AbiParam {
  name: string
  type: string
  indexed?: boolean
  components?: AbiParam[]
  internalType?: string
}

interface HardhatArtifact {
  contractName?: string
  abi: AbiItem[]
  bytecode?: string
}

/**
 * Generate TypeScript client from an EVM ABI file (Hardhat artifact or Foundry output).
 */
export function generateFromAbi(
  schemaPath: string,
  outDir: string,
  config?: Partial<CodegenConfig>,
): CodegenOutput {
  const raw = readFileSync(schemaPath, 'utf-8')
  const artifact: HardhatArtifact = JSON.parse(raw)
  const abi = artifact.abi
  const contractName = artifact.contractName
    ?? schemaPath.split('/').pop()?.replace('.json', '')
    ?? 'Contract'

  const features = config?.features ?? {
    types: true,
    instructions: true,
    errors: true,
    events: true,
  }

  const files: CodegenOutput['files'] = []
  logger.info(`Generating client for ${contractName}...`)

  // Always generate the ABI const export
  files.push({ path: 'contract.ts', content: generateContract(contractName, abi) })

  if (features.types !== false) {
    const content = generateTypes(contractName, abi)
    if (content) files.push({ path: 'types.ts', content })
  }

  if (features.events !== false) {
    const content = generateEvents(contractName, abi)
    if (content) files.push({ path: 'events.ts', content })
  }

  if (features.errors !== false) {
    const content = generateErrors(contractName, abi)
    if (content) files.push({ path: 'errors.ts', content })
  }

  // Barrel export
  const barrel = files.map(f => f.path)
    .filter(p => p !== 'index.ts')
    .map(p => `export * from './${p.replace('.ts', '')}'`)
    .join('\n')
  files.push({
    path: 'index.ts',
    content: `// Auto-generated by Polyq — do not edit\n\n${barrel}\n`,
  })

  // Write to disk
  const contractDir = join(outDir, camelToKebab(contractName))
  mkdirSync(contractDir, { recursive: true })
  for (const file of files) {
    writeFileSync(join(contractDir, file.path), file.content, 'utf-8')
    logger.success(`  → ${file.path}`)
  }

  return { files }
}

function generateContract(name: string, abi: AbiItem[]): string {
  const lines = [
    '// Auto-generated by Polyq — do not edit',
    `// ABI and addresses for ${name}`,
    '',
    `export const ${toConstCase(name)}_ABI = ${JSON.stringify(abi, null, 2)} as const`,
    '',
    `export type ${name}Abi = typeof ${toConstCase(name)}_ABI`,
    '',
    `/**`,
    ` * Contract addresses per network. Add your deployed addresses here.`,
    ` */`,
    `export const ${toConstCase(name)}_ADDRESS: Record<string, \`0x\${string}\`> = {`,
    `  // localhost: '0x...',`,
    `  // sepolia: '0x...',`,
    `  // mainnet: '0x...',`,
    `}`,
    '',
  ]
  return lines.join('\n')
}

function generateTypes(name: string, abi: AbiItem[]): string | null {
  const functions = abi.filter(i => i.type === 'function')
  if (functions.length === 0) return null

  const lines = [
    '// Auto-generated by Polyq — do not edit',
    `// Function types for ${name}`,
    '',
  ]

  for (const fn of functions) {
    if (!fn.name) continue

    // Input args
    if (fn.inputs?.length) {
      const typeName = `${pascalCase(fn.name)}Args`
      lines.push(`export interface ${typeName} {`)
      for (const input of fn.inputs) {
        const paramName = input.name || `_${fn.inputs.indexOf(input)}`
        lines.push(`  ${paramName}: ${mapAbiType(input)}`)
      }
      lines.push('}')
      lines.push('')
    }

    // Return type
    if (fn.outputs?.length) {
      const returnName = `${pascalCase(fn.name)}Return`
      if (fn.outputs.length === 1) {
        const output = fn.outputs[0]
        const outputName = output.name || 'value'
        lines.push(`export interface ${returnName} {`)
        lines.push(`  ${outputName}: ${mapAbiType(output)}`)
        lines.push('}')
      } else {
        lines.push(`export interface ${returnName} {`)
        for (const output of fn.outputs) {
          const outputName = output.name || `_${fn.outputs.indexOf(output)}`
          lines.push(`  ${outputName}: ${mapAbiType(output)}`)
        }
        lines.push('}')
      }
      lines.push('')
    }
  }

  return lines.length > 3 ? lines.join('\n') : null
}

function generateEvents(name: string, abi: AbiItem[]): string | null {
  const events = abi.filter(i => i.type === 'event')
  if (events.length === 0) return null

  const lines = [
    '// Auto-generated by Polyq — do not edit',
    `// Event types for ${name}`,
    '',
  ]

  for (const event of events) {
    if (!event.name) continue
    const typeName = `${event.name}Event`
    lines.push(`export interface ${typeName} {`)
    for (const input of event.inputs ?? []) {
      const paramName = input.name || `_${event.inputs!.indexOf(input)}`
      lines.push(`  ${paramName}: ${mapAbiType(input)}`)
    }
    lines.push('}')
    lines.push('')
  }

  return lines.length > 3 ? lines.join('\n') : null
}

function generateErrors(name: string, abi: AbiItem[]): string | null {
  const errors = abi.filter(i => i.type === 'error')
  if (errors.length === 0) return null

  const lines = [
    '// Auto-generated by Polyq — do not edit',
    `// Custom errors for ${name}`,
    '',
  ]

  for (const error of errors) {
    if (!error.name) continue
    if (error.inputs?.length) {
      lines.push(`export interface ${error.name}Error {`)
      for (const input of error.inputs) {
        const paramName = input.name || `_${error.inputs.indexOf(input)}`
        lines.push(`  ${paramName}: ${mapAbiType(input)}`)
      }
      lines.push('}')
    } else {
      lines.push(`export type ${error.name}Error = Record<string, never>`)
    }
    lines.push('')
  }

  return lines.length > 3 ? lines.join('\n') : null
}

function mapAbiType(param: AbiParam): string {
  const t = param.type
  // Array check MUST come first — 'bytes[]' should be array, not scalar bytes
  if (t.endsWith('[]')) {
    const inner = { ...param, type: t.slice(0, -2) }
    return `${mapAbiType(inner)}[]`
  }
  if (t === 'address') return '`0x${string}`'
  if (t === 'bool') return 'boolean'
  if (t === 'string') return 'string'
  if (t.startsWith('uint') || t.startsWith('int')) return 'bigint'
  if (t.startsWith('bytes')) return '`0x${string}`'
  if (t === 'tuple' && param.components) {
    const fields = param.components.map(c => `${c.name}: ${mapAbiType(c)}`).join(', ')
    return `{ ${fields} }`
  }
  return 'unknown'
}

function pascalCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function toConstCase(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, '$1_$2').toUpperCase()
}

function camelToKebab(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}
