import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve, join } from 'pathe'
import consola from 'consola'
import type { CodegenConfig } from '../../config/types'

const logger = consola.withTag('helm:codegen')

export interface CodegenOutput {
  files: { path: string, content: string }[]
}

interface AnchorIdl {
  address: string
  metadata: { name: string, version: string, spec: string }
  instructions: AnchorInstruction[]
  accounts: AnchorAccount[]
  types: AnchorTypeDef[]
  errors?: AnchorError[]
  events?: AnchorEvent[]
}

interface AnchorInstruction {
  name: string
  discriminator: number[]
  accounts: AnchorInstructionAccount[]
  args: AnchorField[]
}

interface AnchorInstructionAccount {
  name: string
  writable?: boolean
  signer?: boolean
  pda?: {
    seeds: AnchorPdaSeed[]
  }
  optional?: boolean
  address?: string
}

interface AnchorPdaSeed {
  kind: 'const' | 'arg' | 'account'
  value?: number[]
  path?: string
  account?: string
}

interface AnchorAccount {
  name: string
  discriminator: number[]
}

interface AnchorTypeDef {
  name: string
  type: {
    kind: 'struct' | 'enum'
    fields?: AnchorField[]
    variants?: AnchorVariant[]
  }
}

interface AnchorField {
  name: string
  type: AnchorType
}

type AnchorType =
  | string
  | { array: [AnchorType, number] }
  | { vec: AnchorType }
  | { option: AnchorType }
  | { defined: { name: string } }
  | { coption: AnchorType }

interface AnchorVariant {
  name: string
  fields?: AnchorField[]
}

interface AnchorError {
  code: number
  name: string
  msg?: string
}

interface AnchorEvent {
  name: string
  discriminator: number[]
}

/**
 * Generate TypeScript client code from an Anchor IDL file.
 */
export function generateFromIdl(
  idlPath: string,
  outDir: string,
  config?: Partial<CodegenConfig>,
): CodegenOutput {
  const raw = readFileSync(idlPath, 'utf-8')
  const idl: AnchorIdl = JSON.parse(raw)
  const features = config?.features ?? {
    types: true,
    instructions: true,
    accounts: true,
    pda: true,
    errors: true,
    events: true,
  }

  const programName = idl.metadata.name
  const files: CodegenOutput['files'] = []

  logger.info(`Generating client for ${programName}...`)

  if (features.types !== false) {
    const content = generateTypes(idl)
    files.push({ path: 'types.ts', content })
  }

  if (features.pda !== false) {
    const content = generatePdaHelpers(idl)
    files.push({ path: 'pda.ts', content })
  }

  if (features.instructions !== false) {
    const content = generateInstructions(idl)
    files.push({ path: 'instructions.ts', content })
  }

  if (features.accounts !== false) {
    const content = generateAccounts(idl)
    files.push({ path: 'accounts.ts', content })
  }

  if (features.errors !== false && idl.errors?.length) {
    const content = generateErrors(idl)
    files.push({ path: 'errors.ts', content })
  }

  // Barrel export
  const barrel = generateBarrel(files.map(f => f.path))
  files.push({ path: 'index.ts', content: barrel })

  // Write files to disk
  const programDir = join(outDir, snakeToKebab(programName))
  mkdirSync(programDir, { recursive: true })

  for (const file of files) {
    const fullPath = join(programDir, file.path)
    writeFileSync(fullPath, file.content, 'utf-8')
    logger.success(`  → ${file.path}`)
  }

  return { files }
}

// --- Type Generation ---

function generateTypes(idl: AnchorIdl): string {
  const lines: string[] = [
    '// Auto-generated by Helm — do not edit',
    `// Source: ${idl.metadata.name} v${idl.metadata.version}`,
    '',
  ]

  for (const typeDef of idl.types ?? []) {
    if (typeDef.type.kind === 'struct') {
      lines.push(`export interface ${typeDef.name} {`)
      for (const field of typeDef.type.fields ?? []) {
        lines.push(`  ${camelCase(field.name)}: ${mapType(field.type)}`)
      }
      lines.push('}')
      lines.push('')
    } else if (typeDef.type.kind === 'enum') {
      const variants = typeDef.type.variants ?? []
      if (variants.every(v => !v.fields || v.fields.length === 0)) {
        // Simple enum — use string union
        lines.push(`export type ${typeDef.name} =`)
        for (let i = 0; i < variants.length; i++) {
          const sep = i < variants.length - 1 ? ' |' : ''
          lines.push(`  | { ${camelCase(variants[i].name)}: Record<string, never> }${sep}`)
        }
        lines.push('')
      } else {
        // Tagged enum with fields
        lines.push(`export type ${typeDef.name} =`)
        for (const variant of variants) {
          if (!variant.fields || variant.fields.length === 0) {
            lines.push(`  | { ${camelCase(variant.name)}: Record<string, never> }`)
          } else {
            lines.push(`  | { ${camelCase(variant.name)}: {`)
            for (const field of variant.fields) {
              lines.push(`      ${camelCase(field.name)}: ${mapType(field.type)}`)
            }
            lines.push('    } }')
          }
        }
        lines.push('')
      }
    }
  }

  return lines.join('\n')
}

// --- PDA Generation ---

function generatePdaHelpers(idl: AnchorIdl): string {
  const lines: string[] = [
    '// Auto-generated by Helm — do not edit',
    `// PDA derivation helpers for ${idl.metadata.name}`,
    '',
    "import { PublicKey } from '@solana/web3.js'",
    '',
    `export const PROGRAM_ID = new PublicKey('${idl.address}')`,
    '',
  ]

  // Collect unique PDAs from all instructions
  const pdas = new Map<string, AnchorInstructionAccount>()
  for (const ix of idl.instructions) {
    for (const acc of ix.accounts) {
      if (acc.pda && !pdas.has(acc.name)) {
        pdas.set(acc.name, acc)
      }
    }
  }

  for (const [name, acc] of pdas) {
    if (!acc.pda) continue
    const seeds = acc.pda.seeds

    // Determine function parameters from non-const seeds
    const params: string[] = []
    const seedExprs: string[] = []

    for (const seed of seeds) {
      if (seed.kind === 'const' && seed.value) {
        const bytes = seed.value
        // Try to decode as UTF-8 string
        const str = Buffer.from(bytes).toString('utf-8')
        if (/^[\x20-\x7E]+$/.test(str)) {
          seedExprs.push(`Buffer.from('${str}')`)
        } else {
          seedExprs.push(`Buffer.from([${bytes.join(', ')}])`)
        }
      } else if (seed.kind === 'account' && seed.path) {
        const paramName = camelCase(seed.path)
        params.push(`${paramName}: PublicKey`)
        seedExprs.push(`${paramName}.toBuffer()`)
      } else if (seed.kind === 'arg' && seed.path) {
        const paramName = camelCase(seed.path)
        params.push(`${paramName}: Buffer`)
        seedExprs.push(paramName)
      }
    }

    const fnName = `derive${pascalCase(name)}`
    const paramStr = params.length > 0
      ? params.join(', ') + ', programId: PublicKey = PROGRAM_ID'
      : 'programId: PublicKey = PROGRAM_ID'

    lines.push(`export function ${fnName}(${paramStr}): [PublicKey, number] {`)
    lines.push(`  return PublicKey.findProgramAddressSync(`)
    lines.push(`    [${seedExprs.join(', ')}],`)
    lines.push(`    programId,`)
    lines.push(`  )`)
    lines.push(`}`)
    lines.push('')
  }

  return lines.join('\n')
}

// --- Instruction Generation ---

function generateInstructions(idl: AnchorIdl): string {
  const lines: string[] = [
    '// Auto-generated by Helm — do not edit',
    `// Instruction builders for ${idl.metadata.name}`,
    '',
    "import { PublicKey, TransactionInstruction, SystemProgram } from '@solana/web3.js'",
    "import type * as types from './types'",
    '',
    `export const PROGRAM_ID = new PublicKey('${idl.address}')`,
    '',
  ]

  for (const ix of idl.instructions) {
    const fnName = `create${pascalCase(ix.name)}Instruction`

    // Build accounts interface
    const accountsInterfaceName = `${pascalCase(ix.name)}Accounts`
    lines.push(`export interface ${accountsInterfaceName} {`)
    for (const acc of ix.accounts) {
      const optional = acc.optional || acc.address ? '?' : ''
      lines.push(`  ${camelCase(acc.name)}${optional}: PublicKey`)
    }
    lines.push('}')
    lines.push('')

    // Build args interface if needed
    const hasArgs = ix.args.length > 0
    const argsInterfaceName = `${pascalCase(ix.name)}Args`
    if (hasArgs) {
      lines.push(`export interface ${argsInterfaceName} {`)
      for (const arg of ix.args) {
        lines.push(`  ${camelCase(arg.name)}: ${mapType(arg.type)}`)
      }
      lines.push('}')
      lines.push('')
    }

    // Build the instruction function
    const params = hasArgs
      ? `accounts: ${accountsInterfaceName}, args: ${argsInterfaceName}`
      : `accounts: ${accountsInterfaceName}`

    lines.push(`export function ${fnName}(${params}): TransactionInstruction {`)
    lines.push(`  const keys = [`)
    for (const acc of ix.accounts) {
      const writable = acc.writable ? 'true' : 'false'
      const signer = acc.signer ? 'true' : 'false'
      if (acc.address) {
        lines.push(`    { pubkey: accounts.${camelCase(acc.name)} ?? new PublicKey('${acc.address}'), isWritable: ${writable}, isSigner: ${signer} },`)
      } else if (acc.optional) {
        lines.push(`    ...(accounts.${camelCase(acc.name)} ? [{ pubkey: accounts.${camelCase(acc.name)}, isWritable: ${writable}, isSigner: ${signer} }] : []),`)
      } else {
        lines.push(`    { pubkey: accounts.${camelCase(acc.name)}, isWritable: ${writable}, isSigner: ${signer} },`)
      }
    }
    lines.push(`  ]`)
    lines.push('')
    lines.push(`  // Discriminator: [${ix.discriminator.join(', ')}]`)
    lines.push(`  const discriminator = Buffer.from([${ix.discriminator.join(', ')}])`)

    if (hasArgs) {
      lines.push(`  // TODO: Serialize args with Borsh`)
      lines.push(`  const data = discriminator`)
    } else {
      lines.push(`  const data = discriminator`)
    }

    lines.push('')
    lines.push(`  return new TransactionInstruction({`)
    lines.push(`    keys,`)
    lines.push(`    programId: PROGRAM_ID,`)
    lines.push(`    data,`)
    lines.push(`  })`)
    lines.push('}')
    lines.push('')
  }

  return lines.join('\n')
}

// --- Account Fetcher Generation ---

function generateAccounts(idl: AnchorIdl): string {
  const lines: string[] = [
    '// Auto-generated by Helm — do not edit',
    `// Account fetchers for ${idl.metadata.name}`,
    '',
    "import { PublicKey, type Connection } from '@solana/web3.js'",
    "import type * as types from './types'",
    '',
    `export const PROGRAM_ID = new PublicKey('${idl.address}')`,
    '',
  ]

  for (const acc of idl.accounts ?? []) {
    const typeName = acc.name
    const fnName = `fetch${pascalCase(acc.name)}`
    const discriminator = acc.discriminator

    lines.push(`/** Account discriminator for ${typeName}: [${discriminator.join(', ')}] */`)
    lines.push(`export const ${constantCase(acc.name)}_DISCRIMINATOR = [${discriminator.join(', ')}] as const`)
    lines.push('')
    lines.push(`/**`)
    lines.push(` * Fetch and deserialize a ${typeName} account.`)
    lines.push(` * Note: Requires an Anchor Program instance for full deserialization.`)
    lines.push(` */`)
    lines.push(`export async function ${fnName}(`)
    lines.push(`  connection: Connection,`)
    lines.push(`  address: PublicKey,`)
    lines.push(`): Promise<types.${typeName} | null> {`)
    lines.push(`  const accountInfo = await connection.getAccountInfo(address)`)
    lines.push(`  if (!accountInfo) return null`)
    lines.push('')
    lines.push(`  // Verify discriminator`)
    lines.push(`  const disc = [...accountInfo.data.subarray(0, 8)]`)
    lines.push(`  const expected = ${constantCase(acc.name)}_DISCRIMINATOR`)
    lines.push(`  if (!disc.every((b, i) => b === expected[i])) {`)
    lines.push(`    throw new Error('Invalid account discriminator for ${typeName}')`)
    lines.push(`  }`)
    lines.push('')
    lines.push(`  // TODO: Borsh deserialize accountInfo.data.subarray(8)`)
    lines.push(`  throw new Error('Full Borsh deserialization not yet implemented — use Anchor Program.account.${camelCase(acc.name)}.fetch() for now')`)
    lines.push('}')
    lines.push('')
  }

  return lines.join('\n')
}

// --- Error Generation ---

function generateErrors(idl: AnchorIdl): string {
  const lines: string[] = [
    '// Auto-generated by Helm — do not edit',
    `// Error codes for ${idl.metadata.name}`,
    '',
  ]

  lines.push('export enum ProgramError {')
  for (const err of idl.errors ?? []) {
    if (err.msg) {
      lines.push(`  /** ${err.msg} */`)
    }
    lines.push(`  ${err.name} = ${err.code},`)
  }
  lines.push('}')
  lines.push('')

  lines.push('export const PROGRAM_ERRORS: Record<number, { name: string, msg: string }> = {')
  for (const err of idl.errors ?? []) {
    lines.push(`  ${err.code}: { name: '${err.name}', msg: '${err.msg ?? err.name}' },`)
  }
  lines.push('}')
  lines.push('')

  lines.push('export function getProgramError(code: number): { name: string, msg: string } | undefined {')
  lines.push('  return PROGRAM_ERRORS[code]')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

// --- Barrel Export ---

function generateBarrel(filePaths: string[]): string {
  const lines: string[] = [
    '// Auto-generated by Helm — do not edit',
    '',
  ]
  for (const fp of filePaths) {
    if (fp === 'index.ts') continue
    const mod = fp.replace('.ts', '')
    lines.push(`export * from './${mod}'`)
  }
  lines.push('')
  return lines.join('\n')
}

// --- Type Mapping ---

function mapType(t: AnchorType): string {
  if (typeof t === 'string') {
    switch (t) {
      case 'bool': return 'boolean'
      case 'u8': case 'u16': case 'u32': case 'i8': case 'i16': case 'i32':
        return 'number'
      case 'u64': case 'u128': case 'i64': case 'i128':
        return 'bigint'
      case 'f32': case 'f64':
        return 'number'
      case 'string': return 'string'
      case 'pubkey': case 'publicKey':
        return 'PublicKey'
      case 'bytes': return 'Uint8Array'
      default: return t
    }
  }

  if ('array' in t) {
    return `${mapType(t.array[0])}[]`
  }
  if ('vec' in t) {
    return `${mapType(t.vec)}[]`
  }
  if ('option' in t) {
    return `${mapType(t.option)} | null`
  }
  if ('coption' in t) {
    return `${mapType(t.coption)} | null`
  }
  if ('defined' in t) {
    return t.defined.name
  }

  return 'unknown'
}

// --- String Utils ---

function camelCase(s: string): string {
  return s.replace(/[_-]([a-z])/g, (_, c) => c.toUpperCase())
}

function pascalCase(s: string): string {
  const cc = camelCase(s)
  return cc.charAt(0).toUpperCase() + cc.slice(1)
}

function constantCase(s: string): string {
  return s
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/[- ]/g, '_')
    .toUpperCase()
}

function snakeToKebab(s: string): string {
  return s.replace(/_/g, '-')
}
